// 桌面桥接单元测试：用受控 Tauri 替身检查命令 DTO、ACL 一致性、锁定竞态和进度过滤；不操作原生 UI。
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const ts=require('typescript');
const root=path.resolve(__dirname,'../..');
function load(invoke=async()=>null,available=true){
  let locked;const exports={};const channels=[];class Channel{constructor(){channels.push(this);}}
  const source=ts.transpileModule(fs.readFileSync(path.join(root,'src/services/desktopBridge.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
  vm.runInNewContext(source,{exports,setTimeout,require(name){if(name.endsWith('/core'))return {Channel,invoke,isTauri:()=>available};if(name.endsWith('/event'))return {listen:async(_,cb)=>{locked=cb;return ()=>{};}};throw new Error(name);}});
  return {bridge:exports.desktopBridge,specs:exports.commandSpecs,channels,lock:()=>locked()};
}
test('explicit named DTOs and cancellation remain intact',async()=>{let received;const {bridge,specs}=load(async(command,args)=>{received={command,args};return {canceled:true};});assert.equal(specs.credentials[0],'credentials');assert.deepEqual(Array.from(specs.credentials[1]),['password','secret','newPassword','newSecret']);const reply=await bridge.call('windowControl',['minimize']);assert.equal(received.command,'window_control');assert.equal(received.args.action,'minimize');assert.equal(reply.value.canceled,true);});
test('lock epoch discards a delayed result',async()=>{let complete;const {bridge,lock}=load(()=>new Promise(resolve=>{complete=resolve;}));const pending=bridge.call('status',[]);await new Promise(setImmediate);lock();complete({secret:'synthetic-only'});const result=await pending;assert.equal(result.ok,false);assert.equal(result.error,'LOCKED');});
test('initialize forwards only the explicit credential DTO',async()=>{let received;const {bridge}=load(async(command,args)=>{received={command,args};return {role:'OWNER'};});const r=await bridge.call('initialize',['public-test-password','public-test-secret','ignored']);assert.equal(r.ok,true);assert.equal(received.command,'initialize');assert.deepEqual(Object.keys(received.args),['password','secret']);assert.equal(received.args.password,'public-test-password');});
test('read retries cannot resurrect a locked session and writes are not retried',async()=>{let attempts=0;const {bridge,lock}=load(async()=>{attempts++;throw 'TRY_LATER';});const pending=bridge.call('getItem',['a']);await new Promise(setImmediate);lock();assert.equal((await pending).error,'LOCKED');assert.equal(attempts,1);assert.equal((await bridge.call('saveItem',[{}])).error,'TRY_LATER');assert.equal(attempts,2);});
test('directed progress rejects stale, finished and non-whitelisted messages',async()=>{let done,args;const {bridge,channels,lock}=load((_,dto)=>{args=dto;return new Promise(r=>done=r);});const updates=[];bridge.onProgress(p=>updates.push(p));const pending=bridge.call('scan',['untrusted-channel']);await new Promise(setImmediate);assert.equal(args.progress,channels[0]);channels[0].onmessage({stage:'scanning'});channels[0].onmessage({stage:'sensitive unexpected payload'});assert.deepEqual(updates,['scanning']);lock();channels[0].onmessage({stage:'processing'});done([]);assert.equal((await pending).error,'LOCKED');channels[0].onmessage({stage:'scanning'});assert.deepEqual(updates,['scanning',null]);});
test('browser mode and arbitrary error contents fail closed',async()=>{assert.equal((await load(undefined,false).bridge.call('status',[])).error,'DESKTOP_REQUIRED');assert.equal((await load(async()=>{throw 'payload containing secrets';}).bridge.call('status',[])).error,'OPERATION_FAILED');});
test('ACL grants exactly the registered host commands to main only',()=>{const capability=JSON.parse(fs.readFileSync(path.join(root,'src-tauri/capabilities/main.json'),'utf8'));assert.deepEqual(capability.windows,['main']);assert.equal(capability.remote,undefined);const build=fs.readFileSync(path.join(root,'src-tauri/build.rs'),'utf8');const main=['main.rs','commands.rs'].map(f=>fs.readFileSync(path.join(root,'src-tauri/src',f),'utf8')).join('\n');const registered=[...build.matchAll(/"([a-z_]+)"/g)].map(m=>m[1]).filter(s=>s!=='');const permissions=capability.permissions.filter(p=>p.startsWith('allow-')).map(p=>p.slice(6).replaceAll('-','_'));assert.deepEqual(permissions.sort(),registered.sort());for(const name of registered)assert.match(main,new RegExp('fn '+name+'\\b'));assert.equal(capability.permissions.some(p=>/^(fs|shell|http):/.test(p)),false);});
