// 新旧协议互操作回归：调用冻结 Node 实现和 Rust 示例，交叉验证读写、签名、恢复、附件及数字规范化。
"use strict";
const {test}=require('node:test');
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const crypto=require('node:crypto');
const core=require('../../reference/legacy/electron/vault-core.cjs');
const exe=path.resolve(__dirname,'../../target/debug/examples/interop'+(process.platform==='win32'?'.exe':''));
const password='Synthetic password 123 😀';
const secret='LL3-'+ '01234567-'.repeat(7)+'01234567';
const bytes=Buffer.from(Array.from({length:256},(_,i)=>i));
const items=[{id:'synthetic-1',title:'测试 日本語 😀',category:'document',username:'0',notes:'line 1\nline 2\u0000\u2028',createdAt:0,updatedAt:9007199254740991,customFields:[{id:'f',name:'扩展',value:'',isSecret:true,type:'totp',extra:{'\u{10000}':1,'\ue000':2}}],attachments:[{id:'a',name:'bytes.bin',type:'application/octet-stream',size:bytes.length,data:'data:application/octet-stream;base64,'+bytes.toString('base64')}]}];
function raw(args){const r=spawnSync(exe,[],{input:JSON.stringify({password,secret,...args}),encoding:'utf8',maxBuffer:40*1024*1024});assert.equal(r.status,0,r.stderr);return JSON.parse(r.stdout);}
function rust(args){const r=raw(args);assert.equal(r.ok,true,r.error);return r.value;}
test('canonical finite IEEE-754 corpus matches Node exactly',()=>{const numbers=[];for(let i=0;i<10000;i++){const hash=crypto.createHash('sha256').update('public-number-vector-'+i).digest();const n=hash.readDoubleLE();if(Number.isFinite(n))numbers.push(n);}assert.equal(rust({op:'canonical',value:numbers}),core.canonical(numbers));});
test('canonical UTF-16 sorting, escaping, JS numeric encoding, missing vs null',()=>{for(const value of [{ '\ue000':1,'\u{10000}':2,missing:undefined,n:null},[-0,1e-7,1e-6,1e20,1e21,9007199254740991,0.002],['\b\f\n\r\t\u0000','😀','\u2028','\\"']])assert.equal(rust({op:'canonical',value}),core.canonical(value));});
test('Node → Rust owner/recovery; Rust edits → Node; secondary unchanged',async()=>{const p=core.provision(await core.create(password,secret,items));const hash=crypto.createHash('sha256').update(core.canonical(p.secondary)).digest('hex');const r=rust({op:'owner',envelope:p.session.envelope});assert.deepEqual(r.data,p.session.data);assert.deepEqual(rust({op:'recovery',envelope:p.session.envelope,primary:p.primary,secondary:p.secondary}).data,r.data);r.data.items[0].notes+=' Rust';const changed=rust({op:'owner',envelope:r.envelope,data:r.data});assert.deepEqual((await core.unlockOwner(changed.envelope,password,secret)).data,r.data);assert.deepEqual(core.unlockRecovery(changed.envelope,p.primary,p.secondary).data,r.data);assert.equal(crypto.createHash('sha256').update(core.canonical(p.secondary)).digest('hex'),hash);});
test('Rust → Node owner/recovery; Node edits → Rust; credentials preserve recovery; rotation rejects old shares',async()=>{const r=rust({op:'create',items,provision:true});const s=await core.unlockOwner(r.envelope,password,secret);assert.deepEqual(s.data.items,items);assert.deepEqual(core.unlockRecovery(r.envelope,r.primary,r.secondary).data,s.data);s.data.items[0].title+=' Node';const changed=core.update(s,s.data);assert.deepEqual(rust({op:'owner',envelope:changed.envelope}).data,changed.data);const nextPassword='New synthetic password';const nextSecret=core.newSecret();const re=rust({op:'rewrap',envelope:changed.envelope,newPassword:nextPassword,newSecret:nextSecret});await assert.rejects(core.unlockOwner(re.envelope,password,secret));assert.deepEqual((await core.unlockOwner(re.envelope,nextPassword,nextSecret)).data,changed.data);assert.deepEqual(core.unlockRecovery(re.envelope,r.primary,r.secondary).data,changed.data);const rotated=rust({op:'rotate',password:nextPassword,secret:nextSecret,envelope:re.envelope});assert.throws(()=>core.unlockRecovery(rotated.envelope,r.primary,r.secondary));assert.deepEqual(core.unlockRecovery(rotated.envelope,rotated.primary,rotated.secondary).data,changed.data);assert.deepEqual(core.unlockRecovery(r.envelope,r.primary,r.secondary).data.items,items);});
test('tampering, wrong credentials, single share, wrong role/generation/identity; heirs cannot write',async()=>{const r=core.provision(await core.create(password,secret,items));const envelope=r.session.envelope;assert.equal(raw({op:'owner',envelope,password:'Incorrect password'}).error,'AUTHENTICATION_FAILED');assert.equal(raw({op:'owner',envelope:{...envelope,revision:9}}).error,'INVALID_SIGNATURE');assert.equal(raw({op:'owner',envelope:{...envelope,extra:true}}).error,'INVALID_FORMAT');for(const secondary of [null,r.primary,{...r.secondary,generation:99},{...r.secondary,id:'wrong'}])assert.equal(raw({op:'recovery',envelope,primary:r.primary,secondary}).ok,false);assert.equal(raw({op:'recovery',envelope,primary:r.primary,secondary:r.secondary,data:r.session.data}).error,'OWNER_REQUIRED');});
test('historical fixtures decrypt in both implementations',()=>{const base=path.resolve(__dirname,'../../reference/legacy/tests/fixtures');const envelope=require(path.join(base,'v3-vault.json'));const primary=require(path.join(base,'v3-primary.json'));const secondary=require(path.join(base,'v3-secondary.json'));assert.deepEqual(rust({op:'recovery',envelope,primary,secondary}).data,core.unlockRecovery(envelope,primary,secondary).data);assert.deepEqual(rust({op:'owner',envelope,password:'Golden fixture password!',secret:'LL3-'+'1'.repeat(64)}).data,core.unlockRecovery(envelope,primary,secondary).data);});
test('UTF-16 password length and item validation agree',async()=>{const p='😀'.repeat(6);assert.deepEqual(rust({op:'create',password:p,items:[]}).data.items,[]);for(const item of [{...items[0],title:'\ufeff'},{...items[0],unexpected:1},{...items[0],updatedAt:9007199254740992},{...items[0],notes:null},{...items[0],attachments:[{...items[0].attachments[0],size:9}]}]){assert.throws(()=>core.validateItems([item]));assert.equal(raw({op:'create',items:[item]}).ok,false);}});

